const locationTerms = {
  "Автобусн.":          { ua: "Автобусн.",          en: "Bus",          position: "prefix", icon: "busStation" },
  "Аеропорт":           { ua: "аероп.",             en: "Airport",      position: "suffix", icon: "airport" },
  "Алея":               { ua: "ал.",                en: "Alley",        position: "suffix" },
  "Бульвар":            { ua: "бульв.",             en: "Boulevard",    position: "suffix" },
  "Веломаршрут":        { ua: "Веломаршрут",        en: "Cycle road",   position: "suffix" },
  "Водосховище":        { ua: "вдсх",               en: "Reservoir",    position: "suffix" },
  "Вокзал":             { ua: "в-зл",               en: "Station",      position: "suffix", icon: "railStation" },
  "Станція":            { ua: "ст.",                en: "Station",      position: "suffix", icon: "railStation" },
  "Селище, хутір":      { ua: "",                   en: "Hamlet",       position: "suffix", icon: "settlement" },
  "Село":               { ua: "",                   en: "Village",      position: "suffix", icon: "settlement" },
  "Вулиця":             { ua: "вул.",               en: "Street",       position: "suffix" },
  "Дорога":             { ua: "Дорога",             en: "Road",         position: "suffix" },
  "Залізничн.":         { ua: "Залізничн.",         en: "Railway",      position: "suffix", icon: "railStation" },
  "Канал":              { ua: "кан.",               en: "Canal",        position: "suffix" },
  "Лінія":              { ua: "лінія",              en: "Line",         position: "suffix" },
  "Лиман":              { ua: "XXX",                en: "XXX",          position: "suffix" },
  "Майдан":             { ua: "Майдан",             en: "Square",       position: "prefix" },
  "Масив (житловий)":   { ua: "XXX",                en: "XXX",          position: "suffix" },
  "Міська електричка":  { ua: "Міська електричка",  en: "Urban Rail",   position: "prefix" },
  "Місто":              { ua: "",                   en: "City",         position: "suffix", icon: "settlement" },
  "Міст":               { ua: "м.",                 en: "Bridge",       position: "suffix", icon: "bridge" },
  "Набережна":          { ua: "наб.",               en: "Embankment",   position: "suffix" },
  "Озеро":              { ua: "оз.",                en: "Lake",         position: "suffix" },
  "Острів":             { ua: "о-в",                en: "Island",       position: "suffix" },
  "Парк":               { ua: "Парк",               en: "Park",         position: "prefix" },
  "Сквер":              { ua: "Сквер",              en: "Park",         position: "prefix" },
  "Провулок":           { ua: "пров.",              en: "Lane",         position: "suffix" },
  "Площа":              { ua: "пл.",                en: "Square",       position: "suffix" },
  "Проїзд":             { ua: "пр-д",               en: "Passage",      position: "suffix" },
  "Проспект":           { ua: "просп.",             en: "Avenue",       position: "suffix" },
  "Річка":              { ua: "р.",                 en: "River",        position: "suffix" },
  "Район (житловий)":   { ua: "XXX",                en: "XXX",          position: "suffix" },
  "Тупик":              { ua: "туп.",               en: "Dead end",     position: "suffix" },
  "Узвіз":              { ua: "уз.",                en: "Descent",      position: "suffix" },
  "Центр міста":        { ua: "центр",              en: "City centre",  position: "suffix", icon: "cityCentre" },
  "Шляхопровід":        { ua: "ш-д",                en: "Overpass",     position: "suffix", icon: "interchange" },
  "Шосе":               { ua: "ш.",                 en: "Highway",      position: "suffix" },
  "Розв'язка":          { ua: "",                   en: "Interchange",  position: "suffix", icon: "interchange" },
  "Порт":               { ua: "",                   en: "Port",         position: "suffix", icon: "port" },
};

export default locationTerms;
